### ISSUE TITLE
CI tests?

### ISSUE THREAD

**Issue by euank** [ennis/openimageio-rs#3]
Is there any interest in running CI on this repo?

I've managed to get it working on linux without too much trouble, so it seems like it would be easy enough to add a .travis.yml or such that runs all the repo's tests for each PR / on master.

Do you have a preferred CI service? Any concerns about getting it set up?
I'm happy to do the small amount of legwork of writing the configuration if that sounds good.

**Comment by ennis** [comment]
Hi, sounds good! I agree that CI would be a good thing to have. I don't have any preferred CI service (I have used travis in the past but i'm open to anything). I don't know how difficult it would be to setup vcpkg on the CI environment though (because right now the native openimageio is fetched through vcpkg).
